config/routes.rb
BasicNestedForm::Application.routes.draw do
 
  get 'parents/display_partial' => 'parents#display_partial'

  resources :parents
  root 'parents#index'

 

  

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :parent
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children, dependent: :destroy
  accepts_nested_attributes_for :children, reject_if: proc { |a| a[:child_name].blank?}, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

def display_partial

  respond_to do |format|
    format.html # show_rec_horses.html.erb
    format.js   # show_rec_horses.js.erb
  end
end


  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parent }
      else
        format.html { render action: 'new' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:parent_name, children_attributes: [:id, :child_name, :parent_id, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicNestedForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= nested_form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_name %><br>
    <%= f.text_field :parent_name %>
  </div>

  <div class="fields_for_children">
    <%= f.fields_for :children  do |child_form| %>
    <%= child_form.label :child_name %>
    <br />
<%= child_form.text_field :child_name %>
<%= child_form.link_to_remove "Remove child" %>

        <% end %>
   
    
  </div>
<p id='my_parent'><%= f.link_to_add "Add child", :children %></p> 

 
   <br />
    <%= f.submit %>
  </div>
<% end %>









<

app/views/parents/edit.html.erb
<h1>Editing parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<h1>Listing parents</h1>

<table>
  <thead>
    <tr>
      <th>Parent name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.parent_name %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent name:</strong>
  <br />
  <%= @parent.parent_name %>
</p>

<p>
  <strong>Child names:</strong>
    <br />
    <% @parent.children.each do |child| %>
    <%= child.child_name %>
    <br />
  <% end %>

</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>